databases:
  - name: budgetapp
    databaseName: budget_app_4s1c
    user: josue

services:
  - type: web
    name: rushanika
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false